/*
 * config.h
 *
 *  Created on: 2015年11月2日
 *      Author: test
 */

#ifndef COMVM_SYSCONFIG_H_
#define COMVM_SYSCONFIG_H_

//硬件版本定义及状态
#define CURRENT_HW_TYPE 2 // 1 = WEMC, 2 = HCU, 3 = WIFI_EMC
#define CURRENT_HW_MODULE 1 // 0 = NULL, 1 = Samsung 6410, 2 = FSL

//SW version control, for internal usage
#define CURRENT_SW_RELEASE 1 //R01 = 0x01 (XQ.HCU.SW.R01.456)
#define CURRENT_SW_DELIVERY 24 //001 = 0x01 (XQ.HCU.SW.R01.456), starting from 100 as 2015/11/02
//= ZJL, 2015 Nov.1, CURRENT_SW_DELIVERY 1
//= ZJL, 2015 Nov.3, CURRENT_SW_DELIVERY 2
//= ZJL, 2015 Nov.4, CURRENT_SW_DELIVERY 3
//= ZJL, 2015 Nov.9, CURRENT_SW_DELIVERY 4
//= ZJL, 2015 Nov.10, CURRENT_SW_DELIVERY 5
//= ZJL, 2015 Nov.12, CURRENT_SW_DELIVERY 6
//= ZJL, 2015 Nov.13, CURRENT_SW_DELIVERY 7
//= ZJL, 2015 Nov.15, CURRENT_SW_DELIVERY 8
//= ZJL, 2015 Nov.16, CURRENT_SW_DELIVERY 9
//= ZJL, 2015 Nov.17, CURRENT_SW_DELIVERY 10
//= ZJL, 2015 Nov.18, CURRENT_SW_DELIVERY 11
//= ZJL, 2015 Nov.19, CURRENT_SW_DELIVERY 12
//= ZJL, 2015 Nov.20, CURRENT_SW_DELIVERY 13
//= ZJL, 2015 Nov.21, CURRENT_SW_DELIVERY 14
//= MYC, 2015 Nov.22, CURRENT_SW_DELIVERY 15
//= ZJL, 2015 Nov.23, CURRENT_SW_DELIVERY 16
//= ZJL, 2015 Nov.24, CURRENT_SW_DELIVERY 17
//= ZJL, 2015 Nov.25, CURRENT_SW_DELIVERY 18
//= ZJL, 2015 Dec.1, CURRENT_SW_DELIVERY 23
//= ZJL, 2015 Dec.2, CURRENT_SW_DELIVERY 24





//TRACE开关，缺省打开
#define TRACE_MSG_ON 2 //1=ALL Message, 2=ALL but TIME-OUT
//undef TRACE_MSG_ON

//DEBUG开关，缺省打开
//#define TRACE_DEBUG_ON 1//on-off TRACE DEBUG Info
#undef TRACE_DEBUG_ON

//可选项通信端口的全局定义，未来需要通过ConfigXml进一步优化
#define COMM_BACK_HAWL_CON 1 //0=NULL, 1=ETHERNET, 2=WIFI, 3=3G4G, 4=USBNET, 5/OTHERS=INVALID
#define COMM_HW_BOARD_ETHERNET 1 //1=ON, 0/OTHERS=OFF
#define COMM_HW_BOARD_WIFI 1 //1=ON, 0/OTHERS=OFF
#define COMM_HW_BOARD_3G4G 1 //1=ON, 0/OTHERS=OFF
#define COMM_HW_BOARD_USBNET 1 //1=ON, 0/OTHERS=OFF
#define COMM_HW_BOARD_GPS 1 //1=ON, 0/OTHERS=OFF
#define COMM_HW_BOARD_LCD 1 //1=ON, 0/OTHERS=OFF
#define COMM_HW_BOARD_ZEEGBE 0 //1=ON, 0/OTHERS=OFF
#define COMM_HW_BOARD_FLASH 1 //1=ON, 0/OTHERS=OFF  TF card
#define COMM_FRONT_MODBUS 1 //1=ON, 0/OTHERS=OFF
#define COMM_HW_BOARD_BLE 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_SPS485 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_SPS232 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_AUDIO 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_CAMERA 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_BLE 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_SENSOR_EMC 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_SENSOR_PM25 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_SENSOR_TEMP 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_SENSOR_HUMID 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_SENSOR_WINDDIR 1 //1=ON, 0/OTHERS=OFF
#define COMM_FRONT_SENSOR_WINDSPD 1 //1=ON, 0/OTHERS=OFF
#define COMM_HW_BOARD_ON 1
#define COMM_HW_BOARD_OFF 0

//定义后台连接网络的接口
//现在采用这种互斥的方式进行定义，以后需要等待HWINV进行PnP，确保多种接口即插即用，随时切换
//多种接口之间的优先级关系，则有程序任务自动决定：ETHERNET > WIFI > USB-OTG2 > 3G4G
//当前版本的做法是，多种接口均启动起来，但如何使用，由CLOUDCONT按照优先级和COMM_BACK_HAWL_CON定义唯一决定

//定义后台CLOUD连接到本地及SAE的地址
#define CLOUD_HTTP_ADDRESS_LOCAL "http://127.0.0.1/test.php"
#define CLOUD_HTTP_ADDRESS_SAE "http://mfuncard.sinaapp.com/callback.php"




#endif /* COMVM_SYSCONFIG_H_ */
