/*
 * sysconf.h
 *
 *  Created on: 2016年1月3日
 *      Author: hitpony
 */

#ifndef L0COMVM_SYSCONFIG_H_
#define L0COMVM_SYSCONFIG_H_

#include "../l0comvm/sysversion.h"
#include "../l0comvm/comtype.h"
#include "../l0comvm/sysdim.h"
#include "../l0comvm/sysengpar.h"
//#include <unistd.h>


/*
 *
 *   全局性控制表，不可以被数据控制表临时改动，只能通过本文件进行修改，然后重新编译获得结果
 *
 */

//进程启动多少的全局控制参数

//工作进程方式
//1=单进程 2=双进程 3=三进程，4=多进程, OTHERS=无效
#define HCU_SYSCFG_PROCESS_WORK_MODE_NULL 		0
#define HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE 	1
#define HCU_SYSCFG_PROCESS_WORK_MODE_DOUBLE 	2
#define HCU_SYSCFG_PROCESS_WORK_MODE_TRIPPLE 	3
#define HCU_SYSCFG_PROCESS_WORK_MODE_MULTI 		4
#define HCU_SYSCFG_PROCESS_WORK_MODE_OTHER 		5
#define HCU_SYSCFG_PROCESS_WORK_MODE_INVALID 	0xFF

//使用了哪一种数据库
#define HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL 		1
#define HCU_SYSCFG_LOCAL_DB_SELECTION_SQLITE3 		2

//定义底层传感器是否起作用的全局定义，由于比较底层，所以这里不考虑使用工参配置的方式
#define HCU_SYSCFG_SENSOR_PRESENT_YES 	1
#define HCU_SYSCFG_SENSOR_PRESENT_NO 	2

//与后台的接口格式
#define HCU_SYSCFG_CLOUD_BH_ITF_STD_NULL 			0
#define HCU_SYSCFG_CLOUD_BH_ITF_STD_ZHB_HJT212 		10  //中环保
#define HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_L2FRAME 	3
#define HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML 		4
#define HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_JASON 	5
#define HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_JDAPP 	6
#define HCU_SYSCFG_CLOUD_BH_ITF_STD_IOT_WEIXIN		7
#define HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_WECHAT 	8
#define HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_QQIOT 	9
#define HCU_SYSCFG_CLOUD_BH_ITF_STD_INVALID 		0xFF

//与后台接口对应的服务器侦听端口
//#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_XML 				9501 //TO BE REMOVED
//#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_ZHB 				9503 //TO BE REMOVED

#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITPXML_HTTP 		9510
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITPXML_TCP 		9511
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITPXML_UDP 		9512
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_ZHB_HJT212_HTTP 	9513
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_ZHB_HJT212_TCP 	9514
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_ZHB_HJT212_UDP 	9515
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_JASON_HTTP 	9516
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_JASON_TCP 	9517
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_JASON_UDP 	9518
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_NBIOT_CJ188_HTTP 	9519
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_NBIOT_CJ188_TCP 	9520
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_NBIOT_CJ188_UDP 	9521
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_NBIOT_QG376_HTTP 	9522
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_NBIOT_QG376_TCP 	9523
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_NBIOT_QG376_UDP 	9524
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_DATA_STREAM_TCP 	9550

#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML 			9511
#define HCU_SYSCFG_CLOUD_BH_ITF_PORT_ZHB_HJT212 		9999 //for UNICOM CLOUD

//模块是否激活
#define HCU_SYSCFG_TASK_PNP_NULL 		0
#define HCU_SYSCFG_TASK_PNP_ON 			1
#define HCU_SYSCFG_TASK_PNP_OFF 		2
#define HCU_SYSCFG_TASK_PNP_INIT 		3
#define HCU_SYSCFG_TASK_PNP_INVALID 	0xFF

//通信媒介选择
#define HCU_SYSCFG_CLOUD_BH_PHY_LINK_NULL 		0
#define HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH  		1
#define HCU_SYSCFG_CLOUD_BH_PHY_LINK_WIFI 		2
#define HCU_SYSCFG_CLOUD_BH_PHY_LINK_3G4G 		3
#define HCU_SYSCFG_CLOUD_BH_PHY_LINK_USBNET 	4
#define HCU_SYSCFG_CLOUD_BH_PHY_LINK_OTHER 		5
#define HCU_SYSCFG_CLOUD_BH_PHY_LINK_INVALID 	0xFF

//定义是否允许初始化TRACE的MODULE和MSGID表单
#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES 	1
#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_NO 	2

//定义固件是否支持升级Hardware Burn Block => HBB
#define HCU_SYSCFG_HBB_FW_UPGRADE_NONE 				0
#define HCU_SYSCFG_HBB_FW_UPGRADE_NO_NEED 			1
#define HCU_SYSCFG_HBB_FW_UPGRADE_YES_STABLE 		2
#define HCU_SYSCFG_HBB_FW_UPGRADE_YES_TRIAL 		3
#define HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH 		4
#define HCU_SYSCFG_HBB_FW_UPGRADE_INVALID 			0xFF

//定义软件升级方式
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_NULL 0
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_UART_DIRECT 1
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_UART_GPRS 2
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_CANITF 3
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_UDISK 4
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_SD_CARD 5
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_USBNET 6
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_ETH_DIRECT 7
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_SPI_DIRECT 8
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_SPI_ETH 9
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_WIRELESS 10
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_ACTIVE_CONNECT 11
#define HCU_SYSCFG_HBB_FW_UPGRADE_METHOD_INVALID 0xFF

//定义双链路的全局工作标签
#define HCU_SYSCFG_CLOUD_BH_LINK_NULL	  	0
#define HCU_SYSCFG_CLOUD_BH_LINK_DEFAULT  	1
#define HCU_SYSCFG_CLOUD_BH_LINK_HOME  		2
#define HCU_SYSCFG_CLOUD_BH_LINK_DUAL_SAME	3
#define HCU_SYSCFG_CLOUD_BH_LINK_INVALID 	0xFF

//传感器汇报给后台采取的形式：按照位执行
#define HCU_SYSCFG_SENSOR_REPORT_MODE_NULL			0
#define HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL	1  //最低第一位
#define HCU_SYSCFG_SENSOR_REPORT_MODE_GROUP			2  //最低第二位
#define HCU_SYSCFG_SENSOR_REPORT_MODE_INVALID 		0xFF


/*
 *
 *   全局性工程参数控制表，可以被中途修改，更可以事先更新好，重启系统让其起到作用
 *   这里的配置项，只是作为缺省参数，一旦工程参数出错或者不可用，这里的缺省参数将会被起作用
 *   这里的参数起到出厂参数的作用，随着工厂版本一起到达现场
 *
 *   !!!!!!链路层互斥的，不能同时启动多重链路，特别是要共享SOCKET等链路形式，所以在具体测试和配置中，需要特别小心!!!!!
 */
#ifdef TARGET_LINUX_ARM
#define HCU_SYSCFG_DURATION_OF_INIT_FB_WAIT_MAX 20000 //in us iso ms, caculate by task_id * this value, to wait for period for SVRCON too much INIT_WAIT_FOR_FB coming at the same time.
#endif

#ifdef TARGET_LINUX_X86
#define HCU_SYSCFG_DURATION_OF_INIT_FB_WAIT_MAX 20000 //in us iso ms, caculate by task_id * this value, to wait for period for SVRCON too much INIT_WAIT_FOR_FB coming at the same time.
#endif

#ifdef TARGET_RASPBERRY_PI3B
#define HCU_SYSCFG_DURATION_OF_INIT_FB_WAIT_MAX 10000 //in us iso ms, caculate by task_id * this value, to wait for period for SVRCON too much INIT_WAIT_FOR_FB coming at the same time.
#endif

//DEBUG开关，缺省打开
#define HCU_SYSCFG_TRACE_DEBUG_ALL_OFF 0 //全关
#define HCU_SYSCFG_TRACE_DEBUG_INF_ON 1  //全开
#define HCU_SYSCFG_TRACE_DEBUG_NOR_ON 2  //普通级
#define HCU_SYSCFG_TRACE_DEBUG_IPT_ON 4  //重要级
#define HCU_SYSCFG_TRACE_DEBUG_CRT_ON 8  //关键级
#define HCU_SYSCFG_TRACE_DEBUG_FAT_ON 16 //致命级

//TRACE开关，缺省打开
#define HCU_SYSCFG_TRACE_MSG_MODE_OFF 0 //全关
#define HCU_SYSCFG_TRACE_MSG_MODE_INVALID 0xFF //无效
#define HCU_SYSCFG_TRACE_MSG_MODE_ALL 1 //放开所有的TRACE模块和消息，该模式将忽略模块和消息的设置
#define HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT 2  //除了所有的TIME_OUT消息
#define HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_HEART_BEAT 3 //除了所有的HEART_BEAT消息
#define HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT 4  //除了所有的TIME_OUT消息
#define HCU_SYSCFG_TRACE_MSG_MODE_ALL_WITH_TIMERID 5 //带有TIMERID的详细信息
#define HCU_SYSCFG_TRACE_MSG_MODE_TIMERID_ONLY 6 //只带有带有TIMERID的详细信息
#define HCU_SYSCFG_TRACE_MSG_MODE_MOUDLE_TO_ALLOW 10  //只通过模块号过滤消息
#define HCU_SYSCFG_TRACE_MSG_MODE_MOUDLE_TO_RESTRICT 11  //只通过模块号过滤消息
#define HCU_SYSCFG_TRACE_MSG_MODE_MOUDLE_FROM_ALLOW 12  //只通过模块号过滤消息
#define HCU_SYSCFG_TRACE_MSG_MODE_MOUDLE_FROM_RESTRICT 13  //只通过模块号过滤消息
#define HCU_SYSCFG_TRACE_MSG_MODE_MOUDLE_DOUBLE_ALLOW 14  //只通过模块号过滤消息
#define HCU_SYSCFG_TRACE_MSG_MODE_MOUDLE_DOUBLE_RESTRICT 15  //只通过模块号过滤消息
#define HCU_SYSCFG_TRACE_MSG_MODE_MSGID_ALLOW 20  //只通过模块号过滤消息
#define HCU_SYSCFG_TRACE_MSG_MODE_MSGID_RESTRICT 21  //只通过模块号过滤消息
#define HCU_SYSCFG_TRACE_MSG_MODE_COMBINE_TO_ALLOW 30  //通过模块和消息枚举
#define HCU_SYSCFG_TRACE_MSG_MODE_COMBINE_TO_RESTRICT 31  //通过模块和消息枚举
#define HCU_SYSCFG_TRACE_MSG_MODE_COMBINE_FROM_ALLOW 32  //通过模块和消息枚举
#define HCU_SYSCFG_TRACE_MSG_MODE_COMBINE_FROM_RESTRICT 33  //通过模块和消息枚举
#define HCU_SYSCFG_TRACE_MSG_MODE_COMBINE_DOUBLE_ALLOW 34  //通过模块和消息枚举
#define HCU_SYSCFG_TRACE_MSG_MODE_COMBINE_DOUBLE_RESTRICT 35  //通过模块和消息枚举

//定义污染值门限值
#define HCU_SENSOR_PM25_VALUE_ALARM_THRESHOLD 3 //瞬时浓度报警值设为3.0mg/m3,当连续5min颗粒物平均浓度高于3.0mg/m3,在线监测系统应能发布报警提示
#define HCU_SENSOR_NOISE_VALUE_ALARM_THRESHOLD 80 //瞬时噪声报警值设为80 dB,在线监测系统应能发布报警提示
#define HCU_SENSOR_HUMID_VALUE_ALARM_THRESHOLD_UP 700 //朗亿测试用,湿度值门限，超过发指令(带温度门限值)给温控仪控制继电器
#define HCU_SENSOR_HUMID_VALUE_ALARM_THRESHOLD_DOWN 600 //朗亿测试用,湿度值门限，低于此值，发指令(带温度值：0)给温控仪控制继电器

//定义致命错误次数门限值，错误累计次数超过此值，程序退出或重启
#define HCU_FATAL_ERROR_CURL_THRESHOLD 90
#define HCU_FATAL_ERROR_DB_THRESHOLD 12
#define HCU_SYSCFG_REBOOT_LOG_FILE  "/var/hcu/reboot.log"
#define HCU_SYSCFG_REBOOT_LOG_DIR  "/var/hcu"

/*
 *
 *   分项目控制的参数
 *
 */

//老旧的AQYC项目
#if (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_AQYC_OBSOLETE_ID)
	//可选项通信端口的全局定义，未来需要通过ConfigXml进一步优化
	//系统启动选项以及网络连接选项
	//现在采用这种互斥的方式进行定义，以后需要等待HWINV进行PnP，确保多种接口即插即用，随时切换
	//多种接口之间的优先级关系，则有程序任务自动决定：ETHERNET > WIFI > USB-OTG2 > 3G4G
	//当前版本的做法是，多种接口均启动起来，但如何使用，由CLOUDCONT按照优先级和COMM_BACK_HAWL_CON定义唯一决定
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE
	#define HCU_COMM_HW_BOARD_ETHERNET HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_HW_BOARD_USBNET HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_HW_BOARD_WIFI HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_HW_BOARD_3G4G HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_HW_BOARD_GPS HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_HW_BOARD_LCD HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_HW_BOARD_LED HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_HW_BOARD_ZEEGBE HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_HW_BOARD_FLASH HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_MODBUS HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_SPSVIRGO HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_AVORION HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_CLOUDVELA HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_I2CBUSLIBRA HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SPIBUSARIES HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_NBIOTCJ188 HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_NBIOTQG376 HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SPS485 HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_SPS232 HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_MICROPHONE HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_CAMERA HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_BLE HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_GPIO HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_I2C HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SPI HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_PWM HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_ADC HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SWITCH HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_RELAY HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_MOTOR HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_EMC HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_SENSOR_PM25 HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_SENSOR_TEMP HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_SENSOR_HUMID HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_SENSOR_WINDDIR HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_SENSOR_WINDSPD HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_SENSOR_NOISE HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_SENSOR_HSMMP HCU_SYSCFG_TASK_PNP_ON
	#define HCU_COMM_FRONT_SENSOR_AIRPRS HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_CO1 HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_LIGHTSTR HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_ALCOHOL HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_HCHO HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_TOXICGAS HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_PM25SHARP HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_IWM HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_IHM HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_IGM HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_SENSOR_IPM HCU_SYSCFG_TASK_PNP_OFF
	#define HCU_COMM_FRONT_CANITF HCU_SYSCFG_TASK_PNP_OFF

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        //连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         //连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           	//缺省设置

	//Timer setting by Shanhun
	#define HCU_EMC_TIMER_DURATION_PERIOD_READ 600
	#define HCU_EMC_TIMER_DURATION_MODBUS_FB 3
	#define HCU_HUMID_TIMER_DURATION_PERIOD_READ 600
	#define HCU_HUMID_TIMER_DURATION_MODBUS_FB 3
	#define HCU_NOISE_TIMER_DURATION_PERIOD_READ 600
	#define HCU_NOISE_TIMER_DURATION_MODBUS_FB 3
	#define HCU_PM25_TIMER_DURATION_PERIOD_READ 600
	#define HCU_PM25_TIMER_DURATION_MODBUS_FB 3
	#define HCU_TEMP_TIMER_DURATION_PERIOD_READ 600
	#define HCU_TEMP_TIMER_DURATION_MODBUS_FB 3
	#define HCU_WINDDIR_TIMER_DURATION_PERIOD_READ 600
	#define HCU_WINDDIR_TIMER_DURATION_MODBUS_FB 3
	#define HCU_WINDSPD_TIMER_DURATION_PERIOD_READ 600
	#define HCU_WINDSPD_TIMER_DURATION_MODBUS_FB 3
	#define HCU_CLOUDVELA_TIMER_DURATION_PERIOD_LINK_HEART_BEAT 600  //in second  //用于链路检测
	#define HCU_CLOUDVELA_TIMER_DURATION_PERIOD_SEND_DATA_BACK 80 //in second
	#define HCU_CLOUDVELA_TIMER_DURATION_PERIOD_CMD_CONTROL_LONG 600  //for cmd control long timer by Shanchun
	#define HCU_CLOUDVELA_TIMER_DURATION_PERIOD_CMD_CONTROL_SHORT 5  //for cmd control short timer by Shanchun
	#define HCU_NBIOTCJ188_TIMER_DURATION_PERIOD_LINK_HEART_BEAT 600  //in second  //用于链路检测
	#define HCU_NBIOTCJ188_TIMER_DURATION_PERIOD_SEND_DATA_BACK 80
	#define HCU_NBIOTQG376_TIMER_DURATION_PERIOD_LINK_HEART_BEAT 600  //in second  //用于链路检测
	#define HCU_NBIOTQG376_TIMER_DURATION_PERIOD_SEND_DATA_BACK 80
	#define HCU_AIRPRS_TIMER_DURATION_PERIOD_READ 600
	#define HCU_CO1_TIMER_DURATION_PERIOD_READ 600
	#define HCU_LIGHTSTR_TIMER_DURATION_PERIOD_READ 600
	#define HCU_ALCOHOL_TIMER_DURATION_PERIOD_READ 600
	#define HCU_HCHO_TIMER_DURATION_PERIOD_READ 600
	#define HCU_TOXICGAS_TIMER_DURATION_PERIOD_READ 600
	#define HCU_PM25SHARP_TIMER_DURATION_PERIOD_READ 60
	#define HCU_IWM_TIMER_DURATION_PERIOD_READ 600
	#define HCU_IHM_TIMER_DURATION_PERIOD_READ 600
	#define HCU_IGM_TIMER_DURATION_PERIOD_READ 600
	#define HCU_IPM_TIMER_DURATION_PERIOD_READ 600
	#define HCU_SYSPM_TIMER_DURATION_PERIOD_WORKING 600
	#define HCU_CANITFLEO_TIMER_WORKING_SCAN_DURATION 10
	#define HCU_ETHERNET_SOCKET_DURATION_PERIOD_RECV 200000

	//定时器，控制摄像头工作周期及时长
	#define HCU_HSMMP_TIMER_DURATION_PERIOD_AVORION_READ 60 //should be 600second = 10分钟, in second
	#define HCU_HSMMP_AVORION_CAPTURE_DURATION_DEFAULT 2 //10 second
	//下面的时间设置，必须是2.5%精度以上，不能设置为固定TIMEOUT时长，否则会出现逻辑错误
	//比如，采样时间为1000秒，则超时 >= 1000*1.025 = 1025
	#define HCU_HSMMP_TIMER_DURATION_AVORION_FB HCU_HSMMP_AVORION_CAPTURE_DURATION_DEFAULT + 10    //通过AVORION的访问，得到结果的时长。这个时间必须大于摄像头干活的时长
	#define HCU_HSMMP_AVORION_REFRESH_RATE_DEFAULT 25 //10 second

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G101_AQYC_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_AQYC12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE   (2001) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
		#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//打开所有模块，为了测试性能
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_TEST_MODE_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 	60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 		90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        //连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         //连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           	//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G201_TEST_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_TEST12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(2001) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
		#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//基于G1/335D的AQYC
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_AQYCG10_335D_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        //连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         //连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           	//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G101_AQYC_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_AQYC12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(1001) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
	#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//基于G2/树莓派的AQYC
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_AQYCG20_RASBERRY_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        //连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         //连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           	//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G201_AQYC_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"AQHJ0QP0100001"//"ABCDEFG_AQYC12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
/*
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITPXML_HTTP
	//#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_ZHB_HJT212
*/

	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_wechat.php"
	//#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"112.64.16.27"
	//#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"XHZN_HCU"
	//#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_ZHB_HJT212
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT               HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	//#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_ZHB_HJT212
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET        HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	//#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_wechat.php"//XiaoHui
	//#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"//XiaoHui
    #define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME			    "https://h5.aiqiworld.com/xhzn/mfunhcu/l1mainentry/cloud_wechat.php"//Aiqi
    #define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.185.177"//Aiqi
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON + HCU_SYSCFG_TRACE_DEBUG_NOR_ON + HCU_SYSCFG_TRACE_DEBUG_IPT_ON + HCU_SYSCFG_TRACE_DEBUG_CRT_ON + HCU_SYSCFG_TRACE_DEBUG_FAT_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(2002) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
	#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_GROUP //可以加INDIVIDUAL，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//数采仪
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_TBSWRG30_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        //连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         //连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           	//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G301_TBSW_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_TBSW12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//后台CLOUVELA选用的帧协议格式
	//系统级参数，非常重要，一旦改变，可能导致后台不通！！！

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(3001) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
	#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//挂墙仪表
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_GQYBG40_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        //连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         //连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           	//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G401_GQYB_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_GQYB12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(4001) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
	#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//CHUNXU智能路灯
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_CXILC_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        //连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         //连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           	//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G211_ILCX_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_ILCX12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(2101) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
		#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//CHUNXU格力空调模块
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_CXGLACM_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON 			HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET 	HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        	//连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         	//连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           		//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G221_GLAM_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_GLAM12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(2201) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
	#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//CHUNXU低功耗抄表
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_NBIOT_LPM_CJ_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        //连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         //连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           	//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G231_NBLP_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_NBLP12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(2301) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
		#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//CHUNXU中等功耗抄表
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_NBIOT_HPM_QG_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        //连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         //连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           	//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G241_NBHP_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_NBHP12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(2401) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
	#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//波峰组合秤上位机
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_BFSC_CBU_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 	60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 		90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        	//连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         	//连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           		//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME 						"HCU_G801_BFSC_RND01"  	//DEVICE NAME，而且必须缺最后两位
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_BFSC12"

	//定义DEFAULT主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义HOME家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义FTP后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	//HCU工作目录
	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//HTTP-RESTFUL服务地址
	#define HCU_SYSCFG_RESTFUL_PRINTER 			"http://localhost/printer/request.php"
	#define HCU_SYSCFG_RESTFUL_DBA 				"http://localhost/dba/request.php"
	#define HCU_SYSCFG_RESTFUL_VISION			"http://localhost/vision/request.php"
	#define HCU_SYSCFG_RESTFUL_AIWGT			"http://localhost:8000/aiwgt/request.php"


	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET 	HCU_SYSCFG_TRACE_DEBUG_NOR_ON + HCU_SYSCFG_TRACE_DEBUG_IPT_ON + HCU_SYSCFG_TRACE_DEBUG_CRT_ON + HCU_SYSCFG_TRACE_DEBUG_FAT_ON
	#define HCU_SYSCFG_TRACE_MSG_SET 	HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(8001) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
	#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//本项目特定部分
	#define HCU_SYSCFG_BFSC_SNR_WS_NBR_MAX 17  //下位机总共有16个秤盘
	#define HCU_SYSCFG_BFSC_CMDJSON_FILE_SIZE_MAX  (1000)    //BFSCUI命令标志文件 （command.json）最大长度
	#define HCU_SYSCFG_BFSC_DB_COLUMN_NUM_MAX   100  //定义BFSC数据表单最大Column个数，方便数据库查询后的存取

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//奥普维尔的OTDR仪表
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_OPWL_OTDR_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        //连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         //连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           	//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME "HCU_G711_OTDR_TMP01"     //DEVICE NAME
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_OTDR12"

	//定义主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"UNICOM_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET HCU_SYSCFG_TRACE_DEBUG_INF_ON //利用以上标示位，确定TRACE的级别
	#define HCU_SYSCFG_TRACE_MSG_SET HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(7101) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
	#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//波峰双线分选组合称流水线上位机
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_BFDF_CBU_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 	60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 		90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        	//连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         	//连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           		//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME 						"HCU_G8100BFDF_RND01"  	//DEVICE NAME，而且必须缺最后两位
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_BFDF12"

	//定义DEFAULT主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"  //"120.55.125.100"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义HOME家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"  //"120.55.125.100"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义FTP后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	//HCU工作目录
	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//HTTP-RESTFUL服务地址
	#define HCU_SYSCFG_RESTFUL_PRINTER 			"http://localhost/printer/request.php"
	#define HCU_SYSCFG_RESTFUL_DBA 				"http://localhost/dba/request.php"
	#define HCU_SYSCFG_RESTFUL_VISION			"http://localhost/vision/request.php"
	#define HCU_SYSCFG_RESTFUL_AIWGT			"http://localhost:8000/aiwgt/request.php"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET 	HCU_SYSCFG_TRACE_DEBUG_NOR_ON + HCU_SYSCFG_TRACE_DEBUG_IPT_ON + HCU_SYSCFG_TRACE_DEBUG_CRT_ON + HCU_SYSCFG_TRACE_DEBUG_FAT_ON
	#define HCU_SYSCFG_TRACE_MSG_SET 	HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(8100) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
	#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//本项目特定部分
	#define HCU_SYSCFG_GENERIC_SNR_WS_NBR_MAX 16
	#define HCU_SYSCFG_BFDF_CMDJSON_FILE_SIZE_MAX  (1000)
	#define HCU_SYSCFG_BFDF_DB_COLUMN_NUM_MAX   100

	#define HCU_SYSCFG_BFDF_EQU_FLOW_NBR_MAX	2  	//流水线数量
	#define HCU_SYSCFG_BFDF_SNC_BOARD_NBR_MAX	4  	//IO板子数量，每一条线的数量，而不是总数量 DEFAULT=4
	#define HCU_SYSCFG_BFDF_HOPPER_IN_ONE_BOARD	8	//每个IO单板中的料斗数量：FIXED CAN NOT CHANGE!
	#define HCU_SYSCFG_BFDF_HOPPER_NBR_MAX		(HCU_SYSCFG_BFDF_SNC_BOARD_NBR_MAX*HCU_SYSCFG_BFDF_HOPPER_IN_ONE_BOARD+1)	//料斗数量   DEFAULT=33，+1是为了简化程序和各个地方的设计
	#define HCU_SYSCFG_BFDF_NODE_BOARD_NBR_MAX 		HCU_SYSCFG_BFDF_SNC_BOARD_NBR_MAX+2  //WGT/SNC统一编址，再加上第０号板子垃圾桶

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


//波峰高速分选称上位机
#elif (HCU_CURRENT_WORKING_PROJECT_ID_UNIQUE == HCU_WORKING_PROJECT_NAME_BFHS_CBU_ID)
	//系统启动选项以及网络连接选项
	#define HCU_SYSCFG_COMM_BACK_HAWL_CON HCU_SYSCFG_CLOUD_BH_PHY_LINK_ETH
	#define HCU_SYSCFG_PROCESS_MODE_SET HCU_SYSCFG_PROCESS_WORK_MODE_SINGLE

	//传感器配置参数
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_MIN_IN_DAYS 	60
	#define HCU_SYSCFG_SNR_DATA_SAVE_DURATION_IN_DAYS 		90

	//本地数据库HCUDB
	#define HCU_SYSCFG_LOCAL_DB_SELECTION_SET HCU_SYSCFG_LOCAL_DB_SELECTION_MYSQL
	#define HCU_SYSCFG_LOCAL_DB_SQLITE3_LOC_AND_FILE "/var/hcu/cfg/hcudb.sqlite"
	#define HCU_SYSCFG_LOCAL_DB_HOST_DEFAULT "localhost"		//连接的服务器地址
	#define HCU_SYSCFG_LOCAL_DB_USER_DEFAULT "root"     		//连接数据库的用户名
	#define HCU_SYSCFG_LOCAL_DB_PSW_DEFAULT  "123456"        	//连接数据库的密码
	#define HCU_SYSCFG_LOCAL_DB_NAME_DEFAULT "hcudb"         	//连接的数据库名称HCU
	#define HCU_SYSCFG_LOCAL_DB_PORT_DEFAULT 0           		//缺省设置

	//Series Port config by Shanchun
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_MODBUS_DEFAULT 0
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_GPS_DEFAULT  4
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_PM25HARP_DEFAULT  2
	#define HCU_SYSCFG_SERIESPORT_NUM_FOR_QRPRINTER_DEFAULT  1
	#define HCU_SYSCFG_SERIESPORT_BAUTRATE_DEFAULT 9600

	//面对服务器，定义本地名字
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_LOCAL 			"http://127.0.0.1/test.php"
	#define HCU_SYSCFG_CLOUD_HCU_NAME 						"HCU_G820_BFHS_RND01"  	//DEVICE NAME，而且必须缺最后两位
	#define HCU_SYSCFG_CLOUD_ZHBMN_NAME 					"ABCDEFG_BFDF12"

	//定义DEFAULT主服务器后台CLOUD地址信息：允许工程配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_DEFAULT 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_DEFAULT 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_DEFAULT 				"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_DEFAULT				HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ITF_STD_SET 		HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_DEFAULT_ST_CODE			22 //工作在缺省的污染物体系编码中

	//定义HOME家服务器后台CLOUD地址信息：程序写死，不得配置
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_HTTP_HOME 			"http://www.hkrob.com/mfunhcu/l1mainentry/cloud_callback_hcu.php"
	#define HCU_SYSCFG_CLOUD_SVR_ADDR_SOCKETIP_HOME 		"121.40.118.33"
	#define HCU_SYSCFG_CLOUD_SVR_NAME_HOME 					"XHZN_HCU"
	#define HCU_SYSCFG_CLOUD_SVR_PORT_HOME					HCU_SYSCFG_CLOUD_BH_ITF_PORT_HUITP_XML
	#define HCU_SYSCFG_CLOUD_SVR_HOME_ITF_STD_SET 			HCU_SYSCFG_CLOUD_BH_ITF_STD_HUITP_XML

	//定义FTP后台SW_SWM的地址
	#define  HCU_SYSCFG_SWM_SERVER_FTP_ADDRESS "ftp://121.40.118.33/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_USER "avorion"
	#define  HCU_SYSCFG_SWM_SERVER_FTP_PWD "Avorion321"

	//HCU工作目录
	#define  HCU_SYSCFG_SWM_LOCAL_RUN_DIR_DEFAULT "/var/hcu/"
	#define  HCU_SYSCFG_SWM_LOCAL_DOWNLOAD_DIR_DEFAULT "/var/hcu/hcu_sw_download/"
	#define  HCU_SYSCFG_SWM_LOCAL_ACTIVE_DIR_DEFAULT "/var/hcu/hcu_sw_active/"
	#define  HCU_SYSCFG_SWM_LOCAL_BACKUP_DIR_DEFAULT "/var/hcu/hcu_sw_backup/"

	//定义本地视频服务器
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_USER  "Avorion321"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_PWD   "avorion"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_DIR_DEFAULT  "/var/www/html/avorion/"
	#define HCU_SYSCFG_VIDEO_STREAM_SERVER_HTTP_DEFAULT "http://192.168.1.232/avorion/"

	//HTTP-RESTFUL服务地址
	#define HCU_SYSCFG_RESTFUL_PRINTER 			"http://localhost:8000/printer/request.php"
	#define HCU_SYSCFG_RESTFUL_DBA 				"http://localhost:8000/dba/request.php"
	#define HCU_SYSCFG_RESTFUL_VISION			"http://localhost:8000/vision/request.php"
	#define HCU_SYSCFG_RESTFUL_AIWGT			"http://localhost:8000/aiwgt/request.php"

	//打印和TRACE开关
	#define HCU_SYSCFG_TRACE_DEBUG_SET 	HCU_SYSCFG_TRACE_DEBUG_NOR_ON + HCU_SYSCFG_TRACE_DEBUG_IPT_ON + HCU_SYSCFG_TRACE_DEBUG_CRT_ON + HCU_SYSCFG_TRACE_DEBUG_FAT_ON
	#define HCU_SYSCFG_TRACE_MSG_SET 	HCU_SYSCFG_TRACE_MSG_MODE_ALL_BUT_TIME_OUT_AND_HEART_BEAT

	//批量生产标志信息，固件升级标识，以及物理烧录信息等
	#define HCU_SYSCFG_HW_PRODUCT_CAT_TYPE 		(8200) //十进制
	#define HCU_SYSCFG_HBB_FW_UPGRADE_SET HCU_SYSCFG_HBB_FW_UPGRADE_YES_PATCH
	#define HCU_SYSCFG_HBB_PHY_BOOT_CFG_FILE	"/var/hcu/cfg/hcuboot.cfg"

	//定义采用量产之前是否采用本地配置静态数据，从而提高开发效率
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MOD_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_MSG_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_TIMER_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES
	#define HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_GENERAL_SET HCU_SYSCFG_INIT_SET_BY_VM_STATIC_TABLE_YES

	//本项目特定部分
	#define HCU_SYSCFG_GENERIC_SNR_WS_NBR_MAX 16
	#define HCU_SYSCFG_BFDF_CMDJSON_FILE_SIZE_MAX  (1000)
	#define HCU_SYSCFG_BFDF_DB_COLUMN_NUM_MAX   100

	//定义传感器是否采用聚合汇报，还是独立汇报的形式
	#define HCU_SYSCFG_SENSOR_REPORT_MODE_SET	HCU_SYSCFG_SENSOR_REPORT_MODE_INDIVIDUAL //可以加GROUP，变成两个都支持的模式

	//定义软件下载干活的缺省次数
	#define HCU_SYSCFG_SW_DOWNLOAD_MAX_TIMES  0x7FFFFFFF


#else
	#error Un-correct constant definition
#endif




#endif /* L0COMVM_SYSCONFIG_H_ */
